language: java
addons:
  sonarcloud:
    organization: "surite-github"
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8
job:
  include:
    - stage: build & unit test
      script: gradle build
    - script: ls
    - stage: code scan
      script: sonar-scanner
