language: java
addons:
  sonarcloud:
    organization: "surite-github"
    token:
      secure: 4a810aa1792d600f97ef232a0ec82428b7b4507f
jdk:
  - oraclejdk8
jobs:
  include:
    - stage: unit test
      script: gradle build
    - stage: code scan
      script: 
        - if [  "$TRAVIS_PULL_REQUEST" == "false" ]; then gradle sonarqube; fi
