language: java
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8
jobs:
  include:
    - stage: unit test
      script: gradle build
    - stage: code scan
      script: gradle sonarqube -Psonarprojectkey=$SONAR_PROJECT_KEY -Psonarprojectname=$SONAR_PROJECT_NAME
