language: java
addons:
  sonarcloud:
    organization: "surite-github"
    token:
      secure: d6647bbc9c567250416c520125003dd52408cbf7
jdk:
  - oraclejdk8
jobs:
  include:
    - stage: unit test
      script: gradle build
    - stage: code scan
      script: gradle sonarqube
